[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.10.4"
egui-macroquad = "0.12.0"
futures = "0.3.26"
tokio = { version = "1.25.0", features = ["full"] }
uuid = "1.3.0"
